name: Test and Build

on:
  pull_request:
    types: [opened]
    branches: ['feature/**']

jobs:
  build-js:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18']

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-verion: ${{ matrix.node-version }}
          registry-url: 'https://registery.npmjs.org'

      - name: Install PNPM
        run: corepack enable && pnpm install --frozen-lockfile

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Run build
        run: pnpm build

  build-java:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12.16.3']

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-verion: ${{ matrix.node-version }}
          registry-url: 'https://registery.npmjs.org'

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Graddle
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Install dependencies
        run: pnpm install

      - name: Build with Gradle
        run: ./gradlew build
